use_frameworks!

platform :ios, '11.0'

target 'SwifterKnife_Example' do
  pod 'SwifterKnife', :path => '../'
  pod 'SnapKit', :git => 'https://github.com/CoderLouie/SnapKit.git', :branch => 'my_source'
  
  target 'SwifterKnife_Tests' do
    inherit! :search_paths

    
  end
end
